config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :users
  resources :sessions
  resources :decks do
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      resources :decks do
        resources :cards
      end
      get 'study' => 'decks#study'
    end
  end

  namespace :benkyo do
    resources :users
    resources :sessions
  end

  get    '/login'      => 'sessions#new'
  delete '/logout'     => 'sessions#destroy'
  post   '/study/:id'  => 'decks#study'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :decks
  validates :username, presence: true, uniqueness: true, length: {in: 3..16}
  # validates :password, presence: true, length: {minimum: 6}
  validates :auth_token, uniqueness: true
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  before_action :authenticate

  def show
    user = User.find(params[:id]);

    render json: user
  end
end

app/controllers/benkyo/sessions_controller.rb
class Benkyo::SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user && @user.authenticate(params['session']['password'])
      auth_log_in(@user)
      redirect_to "http://localhost:8080/decks;auth=#{@user.auth_token};user=#{@user.id}"
    else
      flash[:error] = "Sorry, username or password was invalid."
      render 'sessions/new'
    end
  end

  def destroy
    @user = get_current_user
    flash[:primary] = "Goodbye, #{@user.username}"
    session.destroy

    redirect_to login_url
  end
end

app/controllers/benkyo/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.auth_token = SecureRandom.urlsafe_base64(n=32)

    if @user.save
      auth_log_in(@user)
      flash[:success] = "#{@user.username} created"
      redirect_to user_url(@user)
    else
      flash[:error] = "Error: #{@user.errors.messages}"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.username} updated"
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    flash[:success] = "Deleted #{@user.username}"
    session.destroy
    @user.destroy
    redirect_to root_url
  end

  private
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/views/benkyo/users/_form.html.erb
<%= form_for :user, url: users_path, html: {class: 'pure-form pure-form-stacked'} do |f| %>
  <div class="form-div">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="form-div">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="form-div">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="form-div">
    <% if @user.new_record? %>
      <%= f.submit "Sign up", class: 'pure-button' %>
    <% else %>
      <%= f.submit "Save Changes", class: 'pure-button' %>
    <% end %>
  </div>
<% end %>

app/views/benkyo/users/edit.html.erb
<div class="container">
  <h2>Edit <%= @user.username %></h2>

  <%= render 'form' %>
</div>

app/views/benkyo/users/new.html.erb
<div class="container">
  <h2>Create a New Account</h2>

  <%= render 'form' %>
</div>

app/views/benkyo/users/show.html.erb
<div class="container">
  <h2><%= @user.username %></h2>

  <%= link_to "Edit User", edit_user_path(@user) %>
  <%= link_to "Delete User", user_path(@user), method: :delete %>
</div>