config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :users
  resources :sessions
  resources :decks do
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      resources :decks do
        resources :cards
      end
      get 'study' => 'decks#study'
    end
  end

  namespace :benkyo do
    resources :users
    resources :sessions
  end

  get    '/login'      => 'sessions#new'
  delete '/logout'     => 'sessions#destroy'
  post   '/study/:id'  => 'decks#study'
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :front, presence: true
  validates :back, presence: true
  belongs_to :deck

  def supermemo(rating)
    q = rating.to_i

    self.efactor = 2.5 unless self.efactor
    self.repetition = 0 unless self.repetition

    self.set_efactor(q)
    self.set_interval
    self.set_due(q)

    self.save
  end

  def set_efactor(q)
    if q < 3
      self.repetition = 1
    else
      self.efactor = self.efactor + (0.1 - (5 - q) * (0.08 + (5 - q) * 0.02))
      self.efactor = 1.3 if self.efactor < 1.3

      self.repetition += 1
    end
  end

  def set_due(q)
    if q < 3
      self.due = Time.now + rand(2..4).minutes
    else
      self.due = Time.now + interval.days
    end
  end

  def set_interval
    if self.repetition == 1
      self.interval = 1
    elsif self.repetition == 2
      self.interval = 6
    else
      self.interval = (self.interval * self.efactor).floor
    end
  end

  private
    def quantify(rating)
      ratings = ['missed', '', 'retry', '', 'good', 'easy']
      ratings.index(rating)
    end

    def check_due
      due = Time.now if !due
    end
end

app/controllers/api/v1/cards_controller.rb
class Api::V1::CardsController < Api::V1::BaseController

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_deck
  before_action :set_card, except: [:index, :new, :create]
  before_action :check_auth

  def index
    @cards = @deck.cards
  end

  def new
    @card = Card.new
  end

  def create
    @card = @deck.cards.new(card_params)
    @card.due = DateTime.now
    if @card.save
      flash[:success] = "#{@card.front} saved"
      redirect_to new_deck_card_url(@deck)
    else
      flash[:error] = "Card not saved"
      render :new
    end
  end

  def update
    if @card.update_attributes(card_params)
      redirect_to deck_cards_url
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to deck_cards_url
  end

  private
    def card_params
      params.require(:card).permit(:front, :back)
    end

    def set_card
      @card = Card.find(params[:id])
    end

    def set_deck
      @deck = Deck.find(params[:deck_id])
    end
end

app/views/cards/_form.html.erb
<%= form_for [@deck, @card],
             html: {class: "pure-form pure-form-stacked"} do |f| %>
  <%= f.label :front %>
  <%= f.text_field :front, autofocus: true %>

  <%= f.label :back %>
  <%= f.text_field :back %>

  <%= f.submit 'Save', class: 'pure-button' %>
<% end %>

app/views/cards/edit.html.erb
<div class="container">
  <h2>Edit <%= @dcard.front %></h2>
</div>

app/views/cards/index.html.erb
<div class="container">
  <h2>Cards Index</h2>
</div>

app/views/cards/new.html.erb
<div class="container">
  <h2>New Card</h2>

  <div class="form-div">
    <%= render 'form' %>
  </div>
  <%= link_to 'Back to decks', decks_path %><br />
  <%= link_to 'Study now', deck_path(@deck) %>
</div>

app/views/cards/show.html.erb
<div class="container">
  <h2><%= @card.front %></h2>
</div>