config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :users
  resources :sessions
  resources :decks do
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      resources :decks do
        resources :cards
      end
      get 'study' => 'decks#study'
    end
  end

  namespace :benkyo do
    resources :users
    resources :sessions
  end

  get    '/login'      => 'sessions#new'
  delete '/logout'     => 'sessions#destroy'
  post   '/study/:id'  => 'decks#study'
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many   :cards, dependent: :destroy
  validates  :title, presence: true

  def get_next_card
    cards.where(["due < ?", Time.now]).reload.order(:due).last || Card.new 
  end
end

app/controllers/api/v1/decks_controller.rb
class Api::V1::DecksController < Api::V1::BaseController
  before_action :authenticate

  def index
    user = User.find(params[:user])
    decks = []

    user.decks.each do |deck|
      decks << {id: deck.id, title: deck.title}
    end

    render json: decks
  end

  def show
    deck_id = params[:id] || params[:deck]
    deck = Deck.find(deck_id)

    p deck.get_next_card

    render json: deck.get_next_card
  end

  def study
    prev_card = Card.find(params[:card])
    puts '*' * 50
    p prev_card

    unless params[:rating] == 'init'
      prev_card.supermemo(params[:rating])
    end

    @deck = Deck.find(Card.find(params[:card]).deck)
    card = @deck.get_next_card.attributes
    card['prev_card'] = "\"#{prev_card.front}\" will be due again #{prev_card.due.strftime('%A %B %-d, %Y')}"
    puts '&' * 50
    p card
    # render json: @deck.get_next_card
    render json: card
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :check_auth
  before_action :assign_deck, except: [:index, :new, :create]

  def index
    user = get_current_user
    @decks = user.decks
  end

  def show
    redirect_to new_deck_card_url(@deck) if @deck.cards.count == 0
  end

  def new
    @deck = Deck.new
  end

  def create
    deck = get_current_user.decks.new(deck_params)

    if deck.save
      redirect_to new_deck_card_path(deck)
    else
      render :new
    end
  end

  def update
    if @deck.update_attributes(deck_params)
      redirect_to(decks_url)
    else
      render :edit
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_url
  end

  def study
    unless params[:rating] == 'init'
      Card.find(params[:card]).supermemo(params[:rating])
    end
    
    render json: { 'card' => @deck.get_next_card, 'message' => 'next card' }
  end

  private
    def deck_params
      params.require(:deck).permit(:title)
    end

    def assign_deck
      @deck = Deck.find(params[:id])
    end
end

app/views/decks/_form.html.erb
<%= form_for @deck, html: {class: 'pure-form pure-form-stacked'} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit class: 'pure-button' %>
<% end %>

app/views/decks/edit.html.erb
<div class="container">
  <h2>Edit <%= @deck.title %></h2>
</div>

app/views/decks/index.html.erb
<div class="container">
  <h2>My Decks:</h2>
  <ul>
    <% @decks.each do |deck| %>
      <li><%= link_to deck.title, deck_path(deck) %></li>
    <% end %>
  </ul>

  <%= link_to "New Deck", new_deck_path, class: "pure-button" %>
  
</div>

app/views/decks/new.html.erb
<div class="container">
  <h2>New Deck</h2>

  <%= render 'form' %>
</div>

app/views/decks/show.html.erb
<% content_for(:body_attributes) do %>
  data-no-turbolink="true"
<% end %>

<div class="container">

  <div class="centered">
    <h2><%= @deck.title %></h2>  
  </div>

  <div id="study-container" class="pure-g">
    <div id="study-console" class="pure-u-1 pure-u-sm-3-5 centered">
      <div id="card-q">
      </div>

      <div id="card-a" style="display:none">
      </div>
    </div>

    <div id="control-console" class="pure-u-1 pure-u-sm-3-5 centered">
      <div id="control-q">
        <button id="show-answer-button" class="pure-button pure-button-primary">
          Show Answer
        </button>
      </div>

      <div id="control-a" style="display:none">
        <button id="missed-card-button" class="red-button pure-button">
          Missed
        </button>
        <button id="retry-card-button" class="pure-button retry-card-button">
          Retry
        </button>
        <button id="good-card-button" class="pure-button good-card-button">
          Good
        </button>
        <button id="easy-card-button" class="pure-button easy-card-button">
          Easy
        </button>
      </div>

      <div id="card-control-console" style="display:none">
        <span id="edit-card-link"><a href="#">edit this card</a></span> |
        <span id="delete-card-link"><a href="#">delete this card</a></span>
      </div>

      <div>
      <%= link_to 'add new cards', new_deck_card_path(@deck), class: "small" %>
      </div>

      <div id="card-message" class="small">
      </div>
    </div>
  </div>
</div>

<%= form_tag '#' %>
  <%= hidden_field_tag 'card-id', @deck.get_next_card.id, id: 'card-id' %>
  <%= hidden_field_tag 'deck-id', @deck.id, id: 'deck-id' %>

<script src="/js/study.js"></script>