config/routes.rb
Rails.application.routes.draw do
  root 'application#index'

  resources :users
  resources :sessions
  resources :decks do
    resources :cards
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
      resources :decks do
        resources :cards
      end
      get 'study' => 'decks#study'
    end
  end

  namespace :benkyo do
    resources :users
    resources :sessions
  end

  get    '/login'      => 'sessions#new'
  delete '/logout'     => 'sessions#destroy'
  post   '/study/:id'  => 'decks#study'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyCard</title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat'
    rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body<%= yield :body_attributes %>>
  <div id="layout">
      <!-- Menu toggle -->
      <a href="#menu" id="menuLink" class="menu-link">
        <!-- Hamburger icon -->
        <span></span>
      </a>

      <div id="menu">
        <div class="pure-menu">
          <a class="pure-menu-heading" href="/">StudyCard</a>

          <ul class="pure-menu-list">
            <% if session[:user_id] %>
              <li class="pure-menu-item">
                <%= link_to 'Sign Out', session_path(session),
                            method: :delete, class: 'pure-menu-link' %>
              </li>
              <li class="pure-menu-item">
                <a href="/decks" class="pure-menu-link">Decks</a>
              </li>
            <% else %>
              <li class="pure-menu-item">
                <%= link_to 'Sign In', new_session_path,
                              class: 'pure-menu-link' %>
              </li>
              <li class="pure-menu-item">
                <a href="/users/new" class="pure-menu-link">New Account</a>
              </li>
            <% end %>

            <li class="pure-menu-item menu-item-divided">
              <a href="#" class="pure-menu-link" >About</a>
            </li>
          </ul>
        </div>
      </div>

      <main id="main" >
        <% unless flash.empty? %>
          <div class="centered" id="flash-div">
            <% flash.each do |key, value| %>
              <%= content_tag :div, value, class: "flash #{key}" %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>

      </main>
    </div>

  <script src="/js/ui.js"></script>
</body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>StudyCard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='https://fonts.googleapis.com/css?family=Montserrat'
    rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>


</html>